# Generated by Django 3.2 on 2022-02-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_location', models.CharField(max_length=50)),
                ('booking_quantity', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
