# Generated by Django 3.2 on 2022-02-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_fname', models.CharField(max_length=50)),
                ('booking_lname', models.CharField(max_length=50)),
                ('booking_email', models.EmailField(max_length=254)),
                ('booking_mobile', models.IntegerField()),
                ('booking_location', models.CharField(max_length=50)),
                ('booking_quantity', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
