# Generated by Django 3.2 on 2022-02-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220220_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_location',
            field=models.CharField(max_length=50, verbose_name='Restuarant Location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_mobile',
            field=models.IntegerField(verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_quantity',
            field=models.CharField(max_length=50, verbose_name='Quantity'),
        ),
    ]
