# Generated by Django 3.2 on 2022-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20220220_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_mobile',
            field=models.CharField(max_length=50, verbose_name='Contact No'),
        ),
    ]
