# Generated by Django 3.2 on 2022-02-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_booking_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
