# Generated by Django 3.2 on 2022-03-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_lname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='reference',
        ),
    ]
