# Generated by Django 3.2 on 2022-03-01 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20220301_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='booking_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='fname',
            new_name='booking_fname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='reference',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='lname',
            new_name='booking_lname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='location',
            new_name='booking_location',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='mobile',
            new_name='booking_mobile',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='quantity',
            new_name='booking_quantity',
        ),
    ]
