# Generated by Django 3.2 on 2022-03-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Booking ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(max_length=50, verbose_name='Contact No')),
                ('location', models.CharField(max_length=50, verbose_name='Restuarant Location')),
                ('quantity', models.CharField(max_length=50, verbose_name='Number of Guests')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
