# Generated by Django 3.2 on 2022-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.IntegerField(choices=[(1, 'London'), (2, 'Glasgow'), (3, 'Cardiff')], verbose_name='Restuarant Location'),
        ),
    ]
