# Generated by Django 3.2 on 2022-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date2',
            field=models.DateTimeField(auto_now=True, verbose_name='Date2'),
        ),
    ]
