# Generated by Django 3.2 on 2022-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date2',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
