# Generated by Django 3.2 on 2022-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20220312_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.CharField(max_length=50, verbose_name='Booking ID'),
        ),
    ]
