# Generated by Django 3.2 on 2022-03-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reference',
        ),
    ]
