# Generated by Django 3.2 on 2022-03-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_booking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
