# Generated by Django 3.2 on 2022-04-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20220326_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fname',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Name'),
        ),
    ]
