# Generated by Django 3.2 on 2022-04-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_booking_fname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'location')},
        ),
    ]
