# Generated by Django 3.2 on 2022-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
