# Generated by Django 3.2 on 2022-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
    ]
